export const notifications = [
  {
    id: 1,
    type: "order",
    message: "Your order #1023 has been shipped 🚚",
    time: "2h ago",
    isRead: false,
  },
  {
    id: 2,
    type: "offer",
    message: "🔥 20% off on Electronics! Limited time deal.",
    time: "5h ago",
    isRead: false,
  },
  {
    id: 3,
    type: "cart",
    message: "Items in your cart are waiting. Complete your checkout!",
    time: "1d ago",
    isRead: true,
  },
  {
    id: 4,
    type: "payment",
    message: "Payment for order #1019 was successful ✅",
    time: "2d ago",
    isRead: true,
  },
  {
    id: 6,
    type: "wishlist",
    message: "A product in your wishlist is now back in stock 🛒",
    time: "5d ago",
    isRead: false,
  },
  {
    id: 7,
    type: "refund",
    message: "Refund for order #1009 has been processed 💳",
    time: "1w ago",
    isRead: true,
  },
];

export const orders = [
  {
    id: "ORD1001",
    name: "Wireless Headphones",
    price: 1999,
    status: "Shipped", // Pending, Shipped, Delivered, Cancelled
    image: "https://images.pexels.com/photos/3747468/pexels-photo-3747468.jpeg",
    paymentMethod: "UPI",
    paymentStatus: "Paid",
    orderedAt: "2025-08-20T10:30:00Z",
    estimatedDelivery: "2025-08-25",
  },
  {
    id: "ORD1002",
    name: "Men's T-Shirt",
    price: 499,
    status: "Delivered",
    image: "https://images.pexels.com/photos/3747468/pexels-photo-3747468.jpeg",
    paymentMethod: "Credit Card",
    paymentStatus: "Paid",
    orderedAt: "2025-08-15T14:15:00Z",
    estimatedDelivery: "2025-08-20",
  },
  {
    id: "ORD1003",
    name: "Laptop Backpack",
    price: 1799,
    status: "Pending",
    image: "https://images.pexels.com/photos/3747468/pexels-photo-3747468.jpeg",
    paymentMethod: "Cash on Delivery",
    paymentStatus: "Unpaid",
    orderedAt: "2025-08-28T09:00:00Z",
    estimatedDelivery: "2025-09-03",
  },
  {
    id: "ORD1004",
    name: "Smartphone",
    price: 29999,
    status: "Cancelled",
    image: "https://images.pexels.com/photos/3747468/pexels-photo-3747468.jpeg",
    paymentMethod: "Net Banking",
    paymentStatus: "Refunded",
    orderedAt: "2025-08-10T16:45:00Z",
    estimatedDelivery: "2025-08-15",
  },
  {
    id: "ORD1005",
    name: "Washing Machine",
    price: 18999,
    status: "Delivered",
    image: "https://images.pexels.com/photos/3747468/pexels-photo-3747468.jpeg",
    paymentMethod: "Debit Card",
    paymentStatus: "Paid",
    orderedAt: "2025-08-05T12:20:00Z",
    estimatedDelivery: "2025-08-10",
  },
];
