export const products = [
  {
    id: 1,
    title: "Wireless Headphones",
    price: 59.99,
    image: "https://images.pexels.com/photos/3394659/pexels-photo-3394659.jpeg",
    category: "Electronics",
    description: "Comfortable over-ear wireless headphones with noise cancellation and long battery life.",
    stock: 20,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Smart Watch",
    price: 129.99,
    image: "https://images.pexels.com/photos/277394/pexels-photo-277394.jpeg",
    category: "Electronics",
    description: "Track your fitness, receive notifications, and monitor your heart rate with this stylish smartwatch.",
    stock: 15,
    rating: 4.2,
  },
  {
    id: 3,
    title: "Bluetooth Speaker",
    price: 39.99,
    image: "https://images.pexels.com/photos/63703/speaker-music-sound-63703.jpeg",
    category: "Electronics",
    description: "Portable Bluetooth speaker with deep bass and waterproof design.",
    stock: 30,
    rating: 4.0,
  },
  {
    id: 4,
    title: "Running Shoes",
    price: 79.99,
    image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
    category: "Fashion",
    description: "Lightweight and durable running shoes for everyday workouts.",
    stock: 25,
    rating: 4.3,
  },
  {
    id: 5,
    title: "Handbag",
    price: 49.99,
    image: "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg",
    category: "Fashion",
    description: "Elegant leather handbag perfect for casual or formal occasions.",
    stock: 10,
    rating: 4.6,
  },
  {
    id: 6,
    title: "Backpack",
    price: 39.99,
    image: "https://images.pexels.com/photos/697694/pexels-photo-697694.jpeg",
    category: "Fashion",
    description: "Spacious backpack with multiple compartments for work and travel.",
    stock: 18,
    rating: 4.1,
  },
  {
    id: 7,
    title: "Desk Lamp",
    price: 24.99,
    image: "https://images.pexels.com/photos/842948/pexels-photo-842948.jpeg",
    category: "Home & Living",
    description: "Minimalist desk lamp with adjustable brightness settings.",
    stock: 22,
    rating: 4.4,
  },
  {
    id: 8,
    title: "Gaming Mouse",
    price: 29.99,
    image: "https://images.pexels.com/photos/196652/pexels-photo-196652.jpeg",
    category: "Electronics",
    description: "High precision gaming mouse with customizable RGB lighting.",
    stock: 40,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Mechanical Keyboard",
    price: 69.99,
    image: "https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg",
    category: "Electronics",
    description: "RGB backlit mechanical keyboard with tactile switches.",
    stock: 12,
    rating: 4.7,
  },
  {
    id: 10,
    title: "Sunglasses",
    price: 19.99,
    image: "https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg",
    category: "Fashion",
    description: "Stylish sunglasses with UV protection.",
    stock: 35,
    rating: 4.1,
  },
  {
    id: 11,
    title: "Coffee Mug",
    price: 9.99,
    image: "https://images.pexels.com/photos/585750/pexels-photo-585750.jpeg",
    category: "Home & Living",
    description: "Ceramic coffee mug with a comfortable grip handle.",
    stock: 50,
    rating: 4.3,
  },
  {
    id: 12,
    title: "Casual T-Shirt",
    price: 14.99,
    image: "https://images.pexels.com/photos/1002644/pexels-photo-1002644.jpeg",
    category: "Fashion",
    description: "Soft cotton casual t-shirt available in multiple colors.",
    stock: 45,
    rating: 4.2,
  },
  {
    id: 13,
    title: "Laptop",
    price: 799.99,
    image: "https://images.pexels.com/photos/18105/pexels-photo.jpg",
    category: "Electronics",
    description: "High-performance laptop suitable for work, study, and gaming.",
    stock: 8,
    rating: 4.6,
  },
  {
    id: 14,
    title: "Tablet",
    price: 299.99,
    image: "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg",
    category: "Electronics",
    description: "Portable tablet with large display and multi-tasking features.",
    stock: 14,
    rating: 4.4,
  },
  {
    id: 15,
    title: "Camera",
    price: 499.99,
    image: "https://images.pexels.com/photos/212372/pexels-photo-212372.jpeg",
    category: "Electronics",
    description: "DSLR camera with 24MP sensor and 4K video recording.",
    stock: 6,
    rating: 4.7,
  },
  {
    id: 16,
    title: "Wrist Watch",
    price: 89.99,
    image: "https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg",
    category: "Fashion",
    description: "Classic wrist watch with stainless steel strap.",
    stock: 20,
    rating: 4.5,
  },
  {
    id: 17,
    title: "Perfume",
    price: 34.99,
    image: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg",
    category: "Beauty",
    description: "Long-lasting fragrance with floral and woody notes.",
    stock: 28,
    rating: 4.2,
  },
  {
    id: 18,
    title: "Office Chair",
    price: 149.99,
    image: "https://images.pexels.com/photos/811036/pexels-photo-811036.jpeg",
    category: "Home & Living",
    description: "Ergonomic office chair with adjustable height and back support.",
    stock: 10,
    rating: 4.6,
  },
  {
    id: 19,
    title: "Cookware Set",
    price: 99.99,
    image: "https://images.pexels.com/photos/3952048/pexels-photo-3952048.jpeg",
    category: "Home & Living",
    description: "Non-stick cookware set with pots, pans, and utensils.",
    stock: 16,
    rating: 4.3,
  },
  {
    id: 20,
    title: "Bicycle",
    price: 199.99,
    image: "https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg",
    category: "Sports",
    description: "Durable mountain bike suitable for off-road and city rides.",
    stock: 9,
    rating: 4.5,
  },
];
